################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
SREC := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
P_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
MAP := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra2l1 \
ra/fsp/src/r_adc \
ra/fsp/src/r_agt \
ra/fsp/src/r_dtc \
ra/fsp/src/r_flash_lp \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_ioport \
ra/fsp/src/r_sci_uart \
ra/fsp/src/r_spi \
ra/fsp/src/r_wdt \
ra/fsp/src/rm_vee_flash \
ra_gen \
src/Device \
src/StateTransition \
src/Task \
src \
src/nfc/DAL/src/R7FA2L1AB2DFP \
src/nfc/NxpNfcRdLib/comps/phCryptoRng/src/Sw \
src/nfc/NxpNfcRdLib/comps/phCryptoRng/src \
src/nfc/NxpNfcRdLib/comps/phCryptoSym/src/Sw \
src/nfc/NxpNfcRdLib/comps/phCryptoSym/src \
src/nfc/NxpNfcRdLib/comps/phKeyStore/src/Rc663 \
src/nfc/NxpNfcRdLib/comps/phKeyStore/src/Sw \
src/nfc/NxpNfcRdLib/comps/phKeyStore/src \
src/nfc/NxpNfcRdLib/comps/phNfcLib/src \
src/nfc/NxpNfcRdLib/comps/phTMIUtils/src \
src/nfc/NxpNfcRdLib/comps/phTools/src \
src/nfc/NxpNfcRdLib/comps/phacDiscLoop/src/Sw \
src/nfc/NxpNfcRdLib/comps/phacDiscLoop/src \
src/nfc/NxpNfcRdLib/comps/phalFelica/src/Sw \
src/nfc/NxpNfcRdLib/comps/phalFelica/src \
src/nfc/NxpNfcRdLib/comps/phalMfc/src/Sw \
src/nfc/NxpNfcRdLib/comps/phalMfc/src \
src/nfc/NxpNfcRdLib/comps/phhalHw/src/PN7462AU \
src/nfc/NxpNfcRdLib/comps/phhalHw/src/Pn5180 \
src/nfc/NxpNfcRdLib/comps/phhalHw/src/Pn5190 \
src/nfc/NxpNfcRdLib/comps/phhalHw/src/Rc663 \
src/nfc/NxpNfcRdLib/comps/phhalHw/src \
src/nfc/NxpNfcRdLib/comps/phpalFelica/src/Sw \
src/nfc/NxpNfcRdLib/comps/phpalFelica/src \
src/nfc/NxpNfcRdLib/comps/phpalI14443p3a/src/Sw \
src/nfc/NxpNfcRdLib/comps/phpalI14443p3a/src \
src/nfc/NxpNfcRdLib/comps/phpalMifare/src/Sw \
src/nfc/NxpNfcRdLib/comps/phpalMifare/src \
src/nfc \
src/nfc/phOsal/src/NullOs \
src/nfc/phOsal/src/NullOs/portable \

